language: ruby
script: 'bundle exec rake'
before_install: 'gem update bundler'
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
